on:
    push:
      branches:
        - master
        - main
      tags: ['*']
    pull_request:
    workflow_dispatch:
jobs:
  docker-build-mwe:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      #- name: setup-docker
      #  uses: docker-practice/actions-setup-docker@v1            
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x docker_build.sh docker_run.sh
      - name: Collect Docker Logs
        uses: jwalton/gh-docker-logs@v2.2.1    
      - name: Run the scripts
        run: |
          ./docker_build.sh
          ./docker_run.sh
          